### ISSUE TITLE
Make OAuth2-Redirect Endpoint Configurable 

### ISSUE THREAD

**Issue by alm0st907** [Azure/azure-functions-openapi-extension#137]
My team is using this package in a slightly different way. We have our own endpoint for the UI trigger so we can add some additional built in endpoints to the swagger page. 

If we use an OAuth2 flow on a function, we can sign in and redirect as expected with the package's built in UI trigger, and the /api/oauth2-redirect.html endpoint will work correctly.

If we us our own trigger to build the UI page, when we sign in, the redirect URL tries to hit /oauth2-redirect.html which fails as it lacks the api/ prefix. All other functionality works as expected.

This seems to be related to the issue and a request made within but I do not see an issue to track it .

#47

**Comment by justinyoo** [comment]
@alm0st907 If you want to use `/oauth2-redirect.html`, you should use the Azure Functions proxy feature, using `proxies.json` because you can't granular control of the `/api` prefix. Therefore the possible solution could be:

1. Use `proxies.json` for `/oauth2-redirect.html`, or
2. Use `host.json` to remove the `/api` prefix from all endpoints and manually add the `/api` prefix to each endpoint's `Route` property that you implement.
