### ISSUE TITLE
Remove Azure Functions app's URL as default base url

### ISSUE THREAD

**Issue by a2741890** [Azure/azure-functions-openapi-extension#390]
**Describe the issue**
When adding new OpenApiServer, I am expecting that I could fully define my own servers(base urls). But still the Azure Functions app's URL is showing after overriding Servers or adding "OpenApi__HostNames" environment variable. The reason to do this is that I am using API management to access the swagger ui, and I don't want to expose the backend Azure function urls. Thank you.

**Expected behavior**
When override Servers, Azure functions app's url should not be added as base url by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/44138757/158946292-984811e4-b793-44a3-8d9f-2765e4deefd6.png)

**Comment by justinyoo** [comment]
@a2741890 Thanks for the issue! Assuming that you're locally running the app because I can see the `localhost`. To omit the `localhost` or hosting application's URL and only want to use API Management's URL, set this property to `false`.

https://github.com/Azure/azure-functions-openapi-extension/blob/e7e2acfa54682c8fa4c93d3bffb9db7716dc2415/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Configurations/DefaultOpenApiConfigurationOptions.cs#L39

Found that this property has not been documented yet. I'll document it soon.

Make sure that you may experiences the CORS error for that case. I'll take further look as well.
