### ISSUE TITLE
New Feature: Support full namespace for model definitions

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#479]
There have been issues due to the duplicated model names, although they are from the different namespaces. For example

```csharp
namespace Hello
{
    class World { ... }
}

namespace Lorem
{
    class World { ... }
}
```

Both classes have the same name, but they are located in the different namespace, which should be recognised as different ones. However, the current logic considers both are the same ones. To figure out this issue, this extension needs to support the full namespace as the model name.

It will be the opt-in feature.

**Comment by MartinWickman** [comment]
Related: https://github.com/Azure/azure-functions-openapi-extension/issues/379

**Comment by dustuu** [comment]
I would like to see this feature implemented in a way that gives users full flexibility over exactly how their model names are generated, not just limiting us to choosing between individual class names or full namespace class names. For example, I have code like this:

```csharp
namespace MyFunctionApp
{
    class AzureFunctionTwo
    {
        class Input { ... }
    }

    class AzureFunctionTwo
    {
        class Input { ... }
    }
}
```

In the solution proposed in previous comments on this issue, my only options for generated model names would be using the full type name of `MyFunctionApp.AzureFunctionTwo.Input` or the individual type name of `Input` (the latter of which would not work due to a conflicting model name with the other `Input` class).

However, I want to drop the namespace and generate a model name like `AzureFunctionTwo_Input`.

The ideal way to allow the functionality proposed in the original version of this issue, along with any other model naming schemes users may want, is to allow users to define their own `Func<System.Type,string>`  to generate model names however they wish.

For example, I could supply a lambda like this where `modelType` is the `System.Type` of my model:

```csharp
modelType => modelType.FullName.Split('.').Last().Replace('+', '_')
```

This would generate a model name like `AzureFunctionTwo_Input` from the type `MyFunctionApp.AzureFunctionTwo.Input`.

Because this implementation of the proposed feature would provide users with full flexibility over how their model names are generated, it could be used to solve any model naming requirement. For example, if a user's requirement was that all model names must be suffixed with the word `Model`, this lambda could be supplied:

```csharp
modelType => $"{modelType.Name}Model"
```

I hope this type of implementation can be considered as the solution to this issue!

**Comment by tadlakha9** [comment]
When we can expect it to be delivered, we have to use this feature in our application

**Comment by ebarnard** [comment]
It would be useful if models could be renamed via an attribute e.g.

```csharp
namespace Hello
{
    [OpenApiName("HelloWorld")]
    class World { ... }
}

namespace Lorem
{
    [OpenApiName("LoremWorld")]
    class World { ... }
}
```

I find that most of the time using the class name for the OpenAPI model name is fine, but occasionally it would be very useful to be able to rename.

@justinyoo I'd be happy to submit a PR for this if you support the idea.

**Comment by justinyoo** [comment]
#610 has addressed this issue. The next `v2-preview` release will contain this fix.
