### ISSUE TITLE
Issue: {"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://xxx.azurewebsites.net/api/swagger.json"}]}

### ISSUE THREAD

**Issue by ssathasivan** [Azure/azure-functions-openapi-extension#98]
I  have includes Open API extension for an Azure Function and is exposing it using an APIM. However when i  browse to  https://xxxxxt.azure-api.net/inventory/swagger/ui . I get the error

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://xxx.azurewebsites.net/api/swagger.json"}]}

Any help is apprciated

**Comment by justinyoo** [comment]
@ssathasivan Thanks for the issue. For more detailed investigation from our end, it would be great if you give us step-by-step repro process.

**Comment by joostvanhassel** [comment]
The problem @ssathasivan is describing is caused by the fact the `swagger/ui` page contains a direct reference to the `swagger.json`, using the hostname of the azure function (`https://xyz.azurewebsites.net`), while the UI is being accessed though a reverse proxy (Azure Api Management) on another hostname (`https://xyz.azure-api.net`).

A user could manually change the hostname of the `swagger.json` in the swagger ui, but it would be great if the hostname of the swagger.json could be set in code.

**Comment by joostvanhassel** [comment]
Perhaps this should be optional: https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs#L72, as the hostname of the swagger document is derived from the first server on the next line. Or this default should only be added of no custom servers are defined.

**Comment by justinyoo** [comment]
@joostvanhassel Thanks for clarifying the issue. I'm working on it.

**Comment by joostvanhassel** [comment]
Great! if you need more info, I can share additional info as we're running into similar issues (due to the use of Azure Frontdoor).

**Comment by justinyoo** [comment]
It's fixed and will be included in the next release!

**Comment by ssathasivan** [comment]
Thank you
